export type RootStackParamList = {
  Home: undefined;
  BasicImageHero: undefined;
  BasicImageHeroDetail: { id: string };
  CardMorph: undefined;
  CardMorphDetail: { id: string };
  ModalHero: undefined;
  ModalHeroDetail: { id: string };
  TransparentModalHero: undefined;
  TransparentModalHeroDetail: { id: string };
  TabsHero: undefined;
  TabsHeroDetail: { id: string };
  SheetHero: undefined;
  SheetHeroDetail: { id: string };
  InPlaceToggle: undefined;
  SpringVsDuration: undefined;
  SpringVsDurationDetail: { id: string; spring: boolean };
  ArcPath: undefined;
  ArcPathDetail: { id: string };
  CustomShuttle: undefined;
  CustomShuttleDetail: { id: string };
  GestureReturn: undefined;
  GestureReturnDetail: { id: string };
  FlatListHero: undefined;
  FlatListHeroDetail: { id: string };
  MultiStep: undefined;
  MultiStepDetail: { id: string; depth: number };
  CoreModalHero: undefined;
};
